from joblib import load
import pandas as pd
import numpy as np
import streamlit as st

st.set_page_config(layout="wide")
st.logo(r"C:\Users\tharu\OneDrive\Pictures\Screenshots 1\Screenshot 2024-07-13 144102.png")
model_poor = load("rfr_user_model.joblib")
input_ct = load("ct_output_poor")
output_sc = load("sc_input_poor")
states = ['Chhattisgarh','Maharashtra','Punjab','Gujarat','Himachal Pradesh','West Bengal','Assam','Kerala','Haryana','Bihar','Uttar Pradesh','Jharkhand','Uttarakhand',
 'Telangana',
 'Karnataka',
 'Rajasthan',
 'Tamil Nadu',
 'Madhya Pradesh',
 'Orissa',
 'Andhra Pradesh']
dist = ['Pali',
 'Jamui',
 'Guna',
 'Hassan',
 'Kodagu',
 'Kangra',
 'Karur',
 'Nayagarh',
 'Thiruvananthapuram',
 'Pudukkottai',
 'Visakhapatnam',
 'Vikarabad',
 'Gumla',
 'Kurnool',
 'Lakhisarai',
 'South Arcot Cuddalore',
 'Dhule',
 'Hoshangabad',
 'Jaisalmer',
 'Indore',
 'Kheri',
 'Bolangir',
 'Gajapati',
 'Parbhani',
 'Virudhunagar Kamarajar',
 'Yamunanagar',
 'Gaya',
 'Saran',
 'Chhindwara',
 'Fatehabad',
 'Swami Madhopur',
 'Lahul & Spiti',
 'Alwar',
 'Sultanpur',
 'Durg',
 'Hissar',
 'Kondagaon',
 'Rewari',
 'Karoli',
 'Santh Ravi Das Nagar Bhadoi',
 'Bastar',
 'Koriya',
 'Sehore',
 'North Arcot Vellore',
 'Satna',
 'Pratapgarh',
 'Shahjahanpur',
 'Sambhal',
 'Uttara Kannada',
 'Shimla',
 'Chamaraja Nagar',
 'Amritsar',
 'Raipur',
 'Udupi',
 'Tikamgarh',
 'Siddipet',
 'Faridkot',
 'Palamau',
 'Hazaribagh',
 'G.B.Nagar',
 'Rudraprayag',
 'Gopalganj',
 'Bhopal',
 'Rajgarh',
 'Udham Singh Nagar',
 'Morbi',
 'Seoni',
 'Dhemaji',
 'Muzaffarpur',
 'Sheopur Kalan',
 'Chhota Udaipur',
 'Chikkaballapur',
 'Wayanad',
 'Chamoli',
 'Akola',
 'Amarawati',
 'Murshidabad',
 'Sonepat',
 'Raisen',
 'Phulbani(Kandhamal)',
 'Dausa',
 'Shajapur',
 'Thanjavur',
 'Rajnandgaon',
 'Kawardha',
 'Chhatarpur',
 'Banaskantha',
 'Jaunpur',
 'Narayanpur',
 'Dhamtari',
 'Hanumangarh',
 'Mahabubnagar',
 'Sonbhadra',
 'Jalna',
 'Mahabubabad',
 'Allahabad',
 'Wardha',
 'Kurukshetra',
 'Coimbatore',
 'Tehri Garhwal',
 'Kishanganj',
 'Hapur',
 'Mirzpur',
 'Buxar',
 'Pilibhit',
 'Nasik',
 'Chandrapur',
 'Tonk',
 'Haridwar',
 'Darjeeling',
 'Panna',
 'Amroha J.B.Fulenagar',
 'Aurangabad',
 'Chengalpattu MGR Kancheepuram',
 'Jabalpur',
 'Basti',
 'Shamli',
 'West Midnapore',
 'Agar Malwa',
 'Rajsamand',
 'Ahmednagar',
 'Tiruchirapalli Trichy',
 'Ambala',
 'Dahod',
 'Barabanki',
 'Karbi Anglong',
 'Taran Taran',
 'Barnala',
 'Bhatinda',
 'Purnea',
 'Surat',
 'Auraiya',
 'Gadag',
 'Jhunjhunu',
 'Giridih',
 'Thiruppur',
 'Jajapur',
 'Dakshin Dinajpur',
 'Bundi',
 'Gandhinagar',
 'Bilashpur',
 'Warangal Urban',
 'Rohtas',
 'Baran',
 'Kamrup(Metro)',
 'Jorhat',
 'Sindhudurg',
 'Chitrakoot',
 'Janjgir',
 'Rampur',
 'Godda',
 'Mungli',
 'Haveri',
 'Dantewara',
 'Katni',
 'Nanded',
 'Bagalkote',
 'Surguja',
 'Dhubri',
 'Vizianagaram',
 'Samastipur',
 'Alirajpur',
 'Dhenkanal',
 'Rayagada',
 'Bhandara',
 'Aligarh',
 'Chidambanar Toothukudi',
 'Bhiwani',
 'Yadadri Bhuvanagiri',
 'Gurgaon',
 'Khammam',
 'Balaghat',
 'Gulbarga',
 'Kanpur Dehat',
 'Bahraich',
 'Alipurduar',
 'Gariaband',
 'Tapi',
 'Shahdol',
 'Azamgarh',
 'Kumurambheem Asifabad',
 'Khagaria',
 'Ganjam',
 'Lucknow',
 'Vidisha',
 'Cachar',
 'Karnal',
 'Amethi C.S.M.Nagar',
 'Hamirpur',
 'Surendranagar',
 'Sonitpur',
 'Bharuch',
 'Ambedkar Nagar',
 'Palwal',
 'Porbandar',
 'Banka',
 'Madhepura',
 'Kalimpong',
 'Mau',
 'Chandauli',
 'Wanaparthy',
 'Damoh',
 'S.A.S Nagar',
 'Baksa',
 'Thane',
 'Nagpur',
 'Bhavnagar',
 'Simdega',
 'Bagpat',
 'West Godavari',
 'Gadchiroli',
 'Thirunelveli',
 'S.B.S Nagar',
 'Krishnagiri',
 'Kapurthala',
 'Chickmagalur',
 'Barpeta',
 'Sirsa',
 'Mumbai City',
 'Kheda',
 'Nagaon',
 'Dibrugarh',
 'Korba',
 'Kinnaur',
 'Kolhapur',
 'Nagapattinam',
 'Raigad',
 'Kutch',
 'Mainpuri',
 'Thrissur',
 'Devbhoomi Dwarka',
 'Vaishali',
 'Mysore',
 'Khandwa',
 'Chittorgarh',
 'Morena',
 'Jalpaiguri',
 'Jalaun',
 'Faizabad',
 'Koppal',
 'Paschim Bardhaman',
 'Devghar Deogarh',
 'Faridabad',
 'Nandurbar',
 'Yeotmal',
 'Kolar',
 'Palakkad',
 'Mahasmund',
 'Pithorgarh',
 'Goalpara',
 'Unnao',
 'Una',
 'Kamareddy',
 'Mayurbhanja',
 'Kollam',
 'Almorah',
 'Datia',
 'Bellary',
 'Keonjhar',
 'Ujjain',
 'Jogulamba Gadwal',
 'Mungair',
 'Gir Somnath',
 'Muzaffarnagar',
 'Khargone',
 'Bokaro',
 'Nirmal',
 'Jind',
 'Raichur',
 'Ganganagar',
 'Neemuch',
 'Lalitpur',
 'Rae - Bareily',
 'Namakkal',
 'Jayashankar Bhuppaly',
 'Kannauj',
 'Bhadradri Kothagudam',
 'Jhansi',
 'Botad',
 'Jalgaon',
 'Angul',
 'Siwan',
 'Nagarkurnool',
 'Mewat',
 'Bhind',
 'Bangalore(Rural)',
 'Mahrajgani',
 'Uttar Dinajpur',
 'Madhubani',
 'Ranchi',
 'Moga',
 'Kanpur Nagar',
 'Jalore',
 'Koraput',
 'Chitradurga',
 'Sirohi',
 'Malappuram',
 'Ramananthapuram',
 'Champaran(East)',
 'Khodrama Koderma',
 'Banswara',
 'Banda',
 'Shri Mukatsar Sahib',
 'Nizamabad',
 'Katihar',
 'Suryapet',
 '24 - Paraganas South',
 'Dholpur',
 'Latur',
 'Gorakhpur',
 'Golaghat',
 'Chennai',
 'Sambalpur',
 'Ashoknagar',
 'Sagar',
 'Firozabad',
 'Satara',
 'Bargarh',
 'Kullu',
 'Bhojpur',
 'Bongaigaon',
 'Dungarpur',
 'Jehanabad',
 'Marigaon',
 'Deoria',
 'Karimnagar',
 'Kasganj Khansi Ram Nagar',
 'Sabarkantha',
 'Chirang',
 'Palghar',
 'Charkhi Dadri',
 'Betul',
 'East Midnapore Purba Midnapore',
 'Bhilwara',
 'Dindori',
 'Jagityal',
 'Jhabua',
 'Vadodara',
 'Moradabad',
 'Idukki',
 'Pathanamthitta',
 'Sikar',
 '24 - Paraganas North',
 'Dindigul Anna',
 'Boudh',
 'Etawah',
 'Fazilka',
 'Balod',
 'Dhanbad',
 'Mahendragarh',
 'Krishna',
 'Jamtara',
 'Narsinghpur',
 'Yadagiri',
 'Ballia',
 'Bijapur',
 'Panipat',
 'The Nilgiris',
 'Chatra',
 'S.P.S.Nellore',
 'Anantapur',
 'Fatehgarh Sahib',
 'Bhagalpur',
 'Perambular',
 'Sivagangai Pasumpon',
 'Puri',
 'Roopnagar',
 'Srikakulam',
 'Mandla',
 'Gonda',
 'Hathras',
 'Chamba',
 'Churu',
 'Kaithal',
 'Kalahandi',
 'Bijnor',
 'Jodhpur',
 'Tiruvarur',
 'Amreli',
 'Prakasam',
 'Darbhanga',
 'Jalandhar',
 'Kannur',
 'Junagadh',
 'Jamnagar',
 'Pune',
 'Beed',
 'Malkangiri',
 'Jhargram',
 'Navsari',
 'North Cachar Hil',
 'Panchkula',
 'Dangs',
 'Hoshiarpur',
 'Sariakela Kharsawan',
 'Buland Shahar',
 'Jaipur',
 'Osmanabad',
 'Kanker',
 'Balasore',
 'Ramgadh',
 'Champaran(West',
 'Gurdaspur',
 'Aravalli',
 'Adilabad',
 'Jashpur',
 'Ludhiana',
 'Pathankot',
 'Bharatpur',
 'Rohtak',
 'Lohardagga',
 'Washim',
 'Champavat',
 'Bidar',
 'Ferozpur',
 'Udalguri',
 'Dewas',
 'Supaul',
 'Anand',
 'Singhbhum West',
 'Sidharthnagar',
 'Rajkot',
 'Ghaziabad',
 'Farrukhabad',
 'Rangareddy',
 'Singhbhum East',
 'Ramanagaram',
 'Villupuram',
 'Dehradun',
 'Saharsa',
 'Dharwad',
 'Peddapally',
 'Sidhi',
 'Madurai',
 'Agra',
 'Gondia',
 'Mandi',
 'Santhal Paragana Dumka',
 'Sukma',
 'Balrampur',
 'Bageshwar',
 'Bhadrak',
 'Solan',
 'Burhanpur',
 'Hailakandi',
 'Santh Kabir Nagar',
 'Dhar',
 'Kanyakumari',
 'Mehsana',
 'Howrah',
 'Dakshina Kannada',
 'Saharanpur',
 'Kokrajhar',
 'Dharmapuri',
 'Latehar',
 'Kottayam',
 'Shimoge',
 'Fatehpur',
 'Mahi Sagar',
 'Mansa',
 'Khurda',
 'Etah',
 'Nadia',
 'Bilaspur',
 'Nainital',
 'Jharsuguda',
 'Periyar(Erode)',
 'Sangareddy',
 'Nawarangpur',
 'Tinsukia',
 'Darrang',
 'Kendrapara',
 'Kasaragod',
 'Jagatsinghapur',
 'Davanagere',
 'Bareilly',
 'Meerut',
 'Ratlam',
 'Sibsagar',
 'Begusarai',
 'Thiruvallur',
 'Singrauli',
 'Nawada',
 'Thiruvannamalai',
 'Kushambi',
 'Hyderabad',
 'Bikaner',
 'Kamrup',
 'Bemetra',
 'Burdwan',
 'East Godavari',
 'Hardoi',
 'Mahoba',
 'Warangal',
 'Pakund Pakur',
 'Sheikapura',
 'Mandya',
 'Sonepur',
 'Sitamarhi',
 'Garhwal',
 'Sitapur',
 'Rewa',
 'Sundargarh',
 'Uttar Kashi',
 'Lakhimpur',
 'Ratnagiri',
 'Kota',
 'Patiala',
 'Ariyalur',
 'Kozhikode',
 'Umaria',
 'Bhabhua Kaimur',
 'Raigarh',
 'Mandsaur',
 'Barmer',
 'Belgaum',
 'Medak',
 'Hingoli',
 'Nalgonda',
 'Varanasi',
 'Chittoor',
 'Jhajjar',
 'Malda',
 'Purulia',
 'Mumbai sub',
 'Kushi Nagar Padrauna',
 'Narmada',
 'Malkaigiri',
 'Guntur',
 'Sangli',
 'Budaun',
 'Udaipur',
 'Karimganj',
 'Jhalawar',
 'Nalanda',
 'Sheohar',
 'Tumkur',
 'Theni',
 'Patna',
 'Araria',
 'Arwal',
 'Sahebganj',
 'Valsad',
 'Ajmer',
 'Shivpuri',
 'Buldhana',
 'Anuppur',
 'Sirmaur',
 'Alappuzha',
 'Baloda Bazar',
 'Cuttack',
 'Gadva Garhwa',
 'Solapur',
 'Khunti',
 'Panchmahal',
 'Nalbari',
 'Cooch Behar',
 'Patan',
 'Eranakulam',
 'Nuapada',
 'Harda',
 'Bangalore(Urban)',
 'Ahmedabad',
 'Kadapa YSR',
 'Nagaur',
 'Salem',
 'Ghazipur',
 'Macherial',
 'Janagaon',
 'Barwani',
 'Mathura',
 'Gwalior',
 'Bankura',
 'Surajpur',
 'Deogarh',
 'Rajanna Siricilla',
 'Hooghly',
 'Shravasti',
 'Sangrur',
 'Birbhum']

# data = pd.DataFrame([[1990, 'Chhattisgarh', 'Durg', 397.90]], 
#                     columns=['Year', 'State Name', 'Dist Name', 'RICE AREA (1000 ha)'])
# filtered_data = input_ct.transform(data)
predicted = False
st.title("Poor Model")
yea = st.slider("select year", 1990, 2017)
stat = st.selectbox("choose state", states)
dis = st.selectbox("choose district", dist)
are = st.text_input("enter area of :rice: planted(ha)", '397.9')
def predict():
    data = pd.DataFrame(
        [[yea, stat, dis, are]], 
        columns=['Year', 'State Name', 'Dist Name', 'RICE AREA (1000 ha)']
    )
    result = model_poor.predict(input_ct.transform(data))
    
    x = output_sc.inverse_transform([result])
    st.success(f"Expected yield is {x[0][0]}")
    
    predicted = True

st.button("predict", on_click=predict)

sentiment_mapping = ["one", "two", "three", "four", "five"]
selected = st.feedback("stars")
if selected is not None:
    st.toast(f"You rated {sentiment_mapping[selected]} star.")